config/routes.rb
Rails.application.routes.draw do

  resources :faqs

  get 'admin'   => "checkins#index"
  scope :admin do
    devise_for :users
    resource :setting, only: [:create,:edit, :update,:show]
    resources :rooms do
      get 'vacancies', on: :collection
      resources 'reservations', except: :index
    end
    resources :checkins, except: [:edit,:update,:destroy] do
      post 'new_roommate',    on: :member
      get  'remove_occupant', on: :member
      get  'remove_utility',  on: :member
      get  'vacate',          on: :member
      post 'transfer',        on: :member
      get  'print',           on: :collection
      resources :notices, except: [:index,:destroy]
    end
    resources :occupants
    resources :utilities
    resources :billings do
      resources :billing_details, except: [:new,:create] do
        post 'add_billing_utilities', on: :member
        delete 'remove_billing_utilities', on: :member
        delete 'remove_billing_occupant', on: :member
        post 'add_billing_occupant', on: :member
      end

      get  'electricity_reading', on: :member
      post 'electricity_reading', on: :member
      get  'water_reading', on: :member
      post 'water_reading', on: :member
      get  'reports',         on: :collection
      get  'print_summary',   on: :member
      get  'final_billing',   on: :member
      post 'final_billing',   on: :member
    end
    resources :users, only: :index

    delete 'admin/billings/:billing_id/billing_details_id/:billing_details_id/billing_utilities/:id' => 'billing_details#remove_billing_utilities', as: :remove_billing_utilities

    put 'billings/:billing_id/billing_details/:billing_details_id/add_comment' => 'billing_details#add_comments', as: :add_billing_detail_comments
  end

  match 'contact' => "home#contact", :via => [:get, :post]
  get   'location'=> "home#location"

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    get 'logout',:to => 'devise/sessions#destroy'
  end

  root 'home#index'

  get  '*path' => redirect('/')

end

app/views/shared/_footer.html.erb
  <!-- footer -->
  <footer class="footer_bg_bottom clearfix">
    <div class="footer_bottom container">
      <div class="clear padding20"></div>
       
      <p>&copy; 2016 All Rights Reserved. &nbsp;</p>

      <div class="clear padding15"></div>
    </div>
  </footer>
  <!-- /footer -->

app/views/shared/_header.html.erb
  <header class="header_bg clearfix">
  <div class="container clearfix">
    <nav>

      <!-- Logo -->
      <div class="logo">
        <a href="index.html"><%= image_tag 'logo.png' %></a>
      </div>
      <!-- /Logo -->

      <!-- Master Nav -->
      <nav class="main-menu">
        <ul>
          <li><%= link_to 'Home', root_url %></li>
          <li><%= link_to 'Location', location_url %></li>
          <li><%= link_to 'FAQ', faqs_url %></li>
        	<li><%= link_to 'Contact', contact_url %></li>
          <% if current_user %>
            <li><%= link_to 'LOG OUT', logout_path %></li>
          <% end %>  
         </ul>
       </nav>
       <!-- /Master Nav -->

    </div>
  </header>

  <div class="clear"></div>

app/views/shared/_menu_sidebar.html.erb
<h3 class="red">Maintenance</h3>
<ul class="contact-address">
  <li><%= link_to 'Rooms', rooms_path %></li>
  <li><%= link_to 'Occupants', occupants_path %></li>
  <li><%= link_to 'Utilities', utilities_path %></li>
  <li><%= link_to 'FAQs', faqs_path %></li>
  <%#= link_to 'Users', users_path %>
  <li><%= link_to 'Settings', setting_path %></li>
</ul>

<h3 class="red">Transactions</h3>
<ul class="contact-address">
  <li><%= link_to 'Checkin In', new_checkin_url %></li>
  <li><%= link_to 'Checkin Details', checkins_url %>
  <li><%= link_to 'Generate Billings', new_billing_url %></li>
  <li><%= link_to 'Billing Details', billings_url %></li>

</ul>

<h3 class="red">Reports</h3>
<ul class="contact-address">
  <li><%= link_to 'Occupancy List', print_checkins_url %></li>
  <li><%= link_to 'Vacancy List', vacancies_rooms_url %></li>
  <li><%= link_to 'Billing Summary', reports_billings_url %></li>
</ul>

<h3 class="red">Account Settings</h3>
<ul class="contact-address">
  <li><%= link_to 'Update Password', edit_user_registration_path %>
</ul>