config/routes.rb
Rails.application.routes.draw do

  resources :faqs

  get 'admin'   => "checkins#index"
  scope :admin do
    devise_for :users
    resource :setting, only: [:create,:edit, :update,:show]
    resources :rooms do
      get 'vacancies', on: :collection
      resources 'reservations', except: :index
    end
    resources :checkins, except: [:edit,:update,:destroy] do
      post 'new_roommate',    on: :member
      get  'remove_occupant', on: :member
      get  'remove_utility',  on: :member
      get  'vacate',          on: :member
      post 'transfer',        on: :member
      get  'print',           on: :collection
      resources :notices, except: [:index,:destroy]
    end
    resources :occupants
    resources :utilities
    resources :billings do
      resources :billing_details, except: [:new,:create] do
        post 'add_billing_utilities', on: :member
        delete 'remove_billing_utilities', on: :member
        delete 'remove_billing_occupant', on: :member
        post 'add_billing_occupant', on: :member
      end

      get  'electricity_reading', on: :member
      post 'electricity_reading', on: :member
      get  'water_reading', on: :member
      post 'water_reading', on: :member
      get  'reports',         on: :collection
      get  'print_summary',   on: :member
      get  'final_billing',   on: :member
      post 'final_billing',   on: :member
    end
    resources :users, only: :index

    delete 'admin/billings/:billing_id/billing_details_id/:billing_details_id/billing_utilities/:id' => 'billing_details#remove_billing_utilities', as: :remove_billing_utilities

    put 'billings/:billing_id/billing_details/:billing_details_id/add_comment' => 'billing_details#add_comments', as: :add_billing_detail_comments
  end

  match 'contact' => "home#contact", :via => [:get, :post]
  get   'location'=> "home#location"

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    get 'logout',:to => 'devise/sessions#destroy'
  end

  root 'home#index'

  get  '*path' => redirect('/')

end

app/models/billing.rb
class Billing < ActiveRecord::Base

  has_many :billing_details

  validates :statement_date,          presence: true
  validates :advance_rent_period,     presence: true
  validates :utilities_reading_period,presence: true

  #validates_uniqueness_of :statement_date
  #validates_uniqueness_of :room_month, scope: [:room_year, :statement_date]
  #validates_uniqueness_of :utilities_month, scope: [:utilities_year, :statement_date]


  MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"]
  YEAR   = [Date.today.year-1, Date.today.year,Date.today.year+1]

  def self.get_details(billing_id)
    where(id = billing_id).includes(:billing_details).order(room_no: :desc)
    #select billings.id, billing_dtls.room_no, (select billing_utilities.id from billing_utilities, billing_dtls where billing_utilities.id = 1 and billing_utilities.billing_dtl_id = billing_dtls.id) as elec from billings, billing_dtls where billings.id = 14 and billings.id = billing_dtls.billing_id;
  end

  def generate_billing_details(user_id)
    checkins = Checkin.all.includes(:checkin_details,:utilities).order(room_no: :asc)
    checkins.each do |checkin|

      # create billing detail
      dtl = billing_details.create(checkin_id: checkin.id,
                                      room_no: checkin.room_no,
                                      user_id: user_id)

      checkin.checkin_details.each do |checkin_detail|
        # automatically set amount except for water and elec
        if (checkin_detail.utility.name == ELECTRICITY)
          utility_period = electricity_reading_period
          amount = 0

        elsif checkin_detail.utility.name == ROOM_RATE
          utility_period = advance_rent_period
          amount = checkin_detail.amount

        elsif checkin_detail.utility.name == WATER_MIN
          utility_period = electricity_reading_period
          amount = checkin_detail.amount

        elsif checkin_detail.utility.name == WATER_EXCESS
          next
        #  utility_period = ''
        #  amount = 0

        else
          utility_period = utilities_reading_period
          amount = checkin_detail.amount
        end

        utl = dtl.billing_utilities.create(utility_name: checkin_detail.utility.name,
                                         utility_period: utility_period,
                                                   rate: checkin_detail.amount,
                                                 amount: amount,
                                             billing_id: id,
                                             sort_order: checkin_detail.utility.sort_order,
                                                user_id: user_id)
      end

      # create billing occupants
      checkin.checkin_occupants.each do |checkin_occupant|
        occupant = dtl.billing_occupants.create(occupant_id: checkin_occupant.occupant_id,
                                                    user_id: user_id)
      end

    end
  end

  def generate_final_billing(checkin_id,user_id)
    checkin = Checkin.where(id: checkin_id).includes(:checkin_details,:utilities)

    # create billing detail
    dtl = billing_details.create(checkin_id: checkin.first.id,
                                    room_no: checkin.first.room_no,
                                    user_id: user_id)

    checkin.first.checkin_details.each do |checkin_detail|
    # automatically set amount except for water and elec
      if (checkin_detail.utility.name != 'Water') && (checkin_detail.utility.name != 'Electricity')
        amount = checkin_detail.amount
      else
        amount = 0
      end

      utl = dtl.billing_utilities.create(utility_name: checkin_detail.utility.name,
                                                 rate: checkin_detail.amount,
                                               amount: amount,
                                           billing_id: id,
                                              user_id: user_id)
    end

    # create billing occupants
    checkin.first.checkin_occupants.each do |checkin_occupant|
      occupant = dtl.billing_occupants.create(occupant_id: checkin_occupant.occupant_id,
                                                  user_id: user_id)
    end
  end

  def self.get_electricity_charges(billing_id)
#    includes(:billing_details,:billing_utilities).where("billing_ = 'Electricity'")
  end



  #def room_period
  #  "#{room_month} #{room_year}"
  #end

  #def utilities_period
  #  "#{utilities_month} #{utilities_year}"
  #end

end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
  before_action :set_billing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /billings
  # GET /billings.json
  def index
    @billings = Billing.all.order(created_at: :desc)
  end

  # GET /billings/1
  # GET /billings/1.json
  def show
    redirect_to billing_billing_details_url(@billing)
  end

  # GET /billings/new
  def new
    @billing = Billing.new
  end

  # GET /billings/1/edit
  def edit
  end

  # POST /billings
  # POST /billings.json
  def create
    @billing = Billing.new(billing_params)
    @billing.user_id = current_user.id

    respond_to do |format|
      if @billing.valid?
        Billing.transaction do
          @billing.save
          @billing.generate_billing_details(current_user.id)
        end
        format.html { redirect_to billing_billing_details_url(@billing), notice: 'Billing was successfully created.' }
        format.json { render :show, status: :created, location: @billing }
      else
        format.html { render :new }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /billings/1
  # PATCH/PUT /billings/1.json
  def update
    @billing.user_id = current_user.id

    respond_to do |format|
      if @billing.update(billing_params)
        format.html { redirect_to billings_url, notice: 'Billing was successfully updated.' }
        #format.json { render :show, status: :ok, location: @billing }
      else
        format.html { render :edit }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /billings/1
  # DELETE /billings/1.json
  def destroy
    @billing.destroy
    respond_to do |format|
      format.html { redirect_to billings_url, notice: 'Billing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def electricity_reading
    @details = BillingUtility.get_electricity(params[:id])

    return unless request.post?

    # update multiple records in one form
    if BillingUtility.update(params['utilities'].keys, params['utilities'].values)
      generate_electricity_amount(@details)
      flash[:notice] = "Electricity Reading successfully added"
      redirect_to billing_billing_details_url(params[:id])
    else
      render :electricity_reading
    end
  end

  def water_reading
    @utilities = BillingUtility.get_water(params[:id])

    return unless request.post?

    # update multiple records in one form
    if BillingUtility.update(params['utilities'].keys, params['utilities'].values)
      generate_water_amount(@utilities)
      flash[:notice] = "Water Reading successfully added"
      redirect_to billing_billing_details_url(params[:id])
    else
      render :water_reading
    end
  end

  def reports
    @billings = Billing.all
  end

  def occupancy_list
    @billing = Billing.find(params[:id])
    @billing_details= @billing.billing_details.includes(:checkin => {:checkin_occupants => :occupant})

    respond_to do |format|
      format.html
      format.csv { send_data @details.to_csv }
      format.xls
      format.pdf do
        html = render_to_string(:layout => false, :action => "occupancy_list.html.erb")
        # many other options
        kit  = PDFKit.new(html, :page_size =>   'A4')
        # you have to give whole path of stylesheet
        kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/print.css"
        # use disposition inline to open in browser. if removed, will automatically download. Another option is 'inline'
        send_data kit.to_pdf, filename: "occupancy_list_as_of_#{@billing.statement_date}.pdf", orientation: "Portrait", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def print_summary
    @billing = BillingDetail.find(params[:id]).billing
    @details = BillingDetail.find_by_sql("select billing_details.id,
                                                 billing_details.room_no,
                                                 billing_details.checkin_id,
                                                 billing_occupants.occupant_id,
                                                 occupants.first_name,
                                                 occupants.last_name,
                                                 (select billing_utilities.amount
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         utility_name = 'Advance Room Rental') as room,
                                                 (select billing_utilities.amount
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         utility_name = 'Electricity') as electricity,
                                                 (select sum(billing_utilities.amount)
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         (utility_name = 'Water (excess)' or utility_name = 'Water (minimum)')) as water,
                                                 (select billing_utilities.amount
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         utility_name = 'Cable TV Installation') as installation,
                                                 (select billing_utilities.amount
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         utility_name = 'Cable TV Subscription') as subscription,
                                                 (select billing_utilities.amount
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         utility_name = 'Cable TV Termination') as termination,
                                                 (select billing_utilities.amount
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         utility_name = 'Basement Parking') as parking,
                                                 (select billing_utilities.amount
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         utility_name = 'Cleaning Fee') as cleaning,
                                                 (select billing_utilities.amount
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         utility_name = 'Transcient Fee') as transcient,
                                                 (select billing_utilities.amount
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         utility_name = 'Penalty') as penalty,
                                                 (select billing_utilities.amount
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         utility_name = 'Damages') as damages,
                                                 (select billing_utilities.amount
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         utility_name = 'Lost Key') as lost_key,
                                                 (select billing_utilities.amount
                                                    from billing_utilities
                                                   where billing_utilities.billing_detail_id = billing_details.id and
                                                         utility_name = 'Locked Out') as locked_out,
                                                (select billing_utilities.amount
                                                            from billing_utilities
                                                           where billing_utilities.billing_detail_id = billing_details.id and
                                                                 utility_name = 'Overage') as overage
                                                    from billing_details,
                                                         billing_occupants,
                                                         occupants
                                           where billing_details.id = billing_occupants.billing_detail_id and

app/helpers/billings_helper.rb
module BillingsHelper
end

app/views/billings/_form.html.erb
<%= form_for(@billing) do |f| %>
  <% if @billing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@billing.errors.count, "error") %> prohibited this billing from being saved:</h2>

      <ul>
      <% @billing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :statement_date %><br/>
    <%= f.text_field :statement_date, id: 'datepicker' %>
  </p>

  <p>
    <%= f.label :advance_rent_period %><br/>
    <%= f.text_field :advance_rent_period %>
    <%#= f.select :room_month, Billing::MONTHS, prompt: "Select month" %>
    <%#= f.select :room_year, Billing::YEAR, prompt: "Select year" %>
  </p>

  <p>
    <%= f.label :electricity_reading_period %><br/>
    <%= f.text_field :electricity_reading_period %>
    <%#= f.select :room_month, Billing::MONTHS, prompt: "Select month" %>
    <%#= f.select :room_year, Billing::YEAR, prompt: "Select year" %>
  </p>

  <p>
    <%= f.label :utilities_period %><br/>
    <%= f.text_field :utilities_reading_period %>
    <%#= f.select :utilities_month, Billing::MONTHS, prompt: "Select month" %>
    <%#= f.select :utilities_year, Billing::YEAR, prompt: "Select year" %>
  </p>

  <div class="actions">
    <%= f.submit %> <%= link_to 'Cancel', checkins_url, class: "styled_links" %>
  </div>
<% end %>

app/views/billings/edit.html.erb
<section class="container clearfix">
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line">Edit Billings</h1>
    <div class="clear"></div>
  </header>
  
  <div class="col_1_4">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>

  <div class="col_3_4 last">
    <h3 class="red">Editing Billing</h3>

    <p id="notice"><%= notice %></p>
    
    <%= render 'form' %>
  </div>
        
  <div class="clear padding15"></div>
</section>  

app/views/billings/electricity_reading.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>

    <div class="col_3_4 last">
      <h3 class="red">Electricity Reading</h3>

      <p id="notice"><%= notice %></p>

      <div class="narrow">
        <%= label_tag 'Room No' %>
        <%= label_tag 'Present' %>
        <%= label_tag 'Previous' %>
        
        <%= '' %>

          <%= form_tag do %>
          <% @details.each do |detail| %>


              <%= fields_for "utilities[]", detail do |f| %>
                  <%= label_tag detail.billing_detail.room_no %>
                  <%= f.text_field 'to' %>
                  <%= f.text_field 'from'   %>
                  <%= diff = detail.to - detail.from %>

                  <br/>
              <% end%>

            <% end%>
            <%= submit_tag %> <%#= link_to 'Back', billing_billing_details_url(params[:id]), class: "styled_links" %> <%= link_to 'Cancel', billings_url, class: "styled_links" %>

          <% end %>
        </div>
    </div>

    <div class="clear padding15"></div>
  </section>

app/views/billings/final_billing.html.erb
<section class="container clearfix">
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line">New Billing Period</h1>
    <div class="clear"></div>
  </header>
  
  <div class="col_1_4">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>
  
  <div class="col_3_4 last">
    <h3 class="red">Final Billing</h3>

    <p id="notice"><%= notice %></p>
    
    <p>
      <%= label_tag :room_no %><%= @checkin.room_no %>
    </p>
    
    <p>
      <%= label_tag :occupants %>
    </p>

    <%= form_tag final_billing_billing_url(@checkin.id), method: :post do %>
      <% if @billing.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@billing.errors.count, "error") %> prohibited this billing from being saved:</h2>

          <ul>
          <% @billing.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
  
      <p>
        <%= label_tag :statement_date %><br/>
        <%= text_field_tag :statement_date, '', id: 'datepicker' %>
      </p>
  
      <p>
        <%= label_tag :advance_rent_period %><br/>
        <%= select_tag :room_month, options_for_select(Billing::MONTHS), prompt: "Select month" %>
        <%= select_tag :room_year,  options_for_select(Billing::YEAR),   prompt: "Select year" %>
      </p>
  
      <p>
        <%= label_tag :utilities_period %><br/>
        <%= select_tag :utilities_month, options_for_select(Billing::MONTHS), prompt: "Select month" %>
        <%= select_tag :utilities_year,  options_for_select(Billing::YEAR),   prompt: "Select year" %>
      </p>

      <div class="actions">
        <%= submit_tag %> <%= link_to 'Cancel', checkins_url, class: "styled_links" %>
      </div>
    <% end %>
  </div>
        
  <div class="clear padding15"></div>
</section>  

app/views/billings/index.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>

  <div class="col_3_4 last">
    <!--h3 class="red">Settings</h3-->

    <h3>Billing Statements</h3>

    <p id="notice"><%= notice %></p>

    <table id="billings">
      <thead>
        <tr>

          <th>Statement Date</th>
          <th>Adv Rent Period</th>
          <th>Utilities Period</th>
          <th>Readings</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @billings.each do |billing| %>
          <tr>
            
            <td><%= billing.statement_date %><%= "*" if billing.final_billing? %></td>
            <td><%= billing.advance_rent_period %></td>
            <td><%= billing.utilities_reading_period %></td>


            <td>
              <%= link_to 'Electricity', electricity_reading_billing_url(billing.id) %>
              <%= link_to 'Water', water_reading_billing_url(billing.id) %>
            </td>
            <td>
              <%= link_to 'Show', billing_billing_details_url(billing) %>
              <%= link_to 'Edit', edit_billing_path(billing) %>
              <%= link_to 'Destroy', billing, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    </div>

    <span><i>*final billings</i></span>

  <div class="clear padding15"></div>

</section>

app/views/billings/new.html.erb
<section class="container clearfix">
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line">New Billing Period</h1>
    <div class="clear"></div>
  </header>
  
  <div class="col_1_4">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>
  
  <div class="col_3_4 last">
    <h3 class="red">New Billing Period</h3>

    <p id="notice"><%= notice %></p>

    <%= render 'form' %>
  </div>
        
  <div class="clear padding15"></div>
</section>  

app/views/billings/print_summary.html.erb
<section class="container clearfix">
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line no_print">Settings</h1>
    <div class="clear"></div>
  </header>

  <div class="col_1_4 no_print">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>

  <div class="col_3_4 last">
    <h3 class="red"><%= @billing.final_billing? ? "Final Billing" : "Billing Statement Summary"%></h3>

    <p><b><%= label_tag :statement_date   %></b>: <%= @billing.statement_date %></p>
    <p><b><%= label_tag  :adv_rent_period %></b>: <%= @billing.advance_rent_period %></p>
    <p><b><%= label_tag :utilities_period %></b>: <%= @billing.utilities_reading_period %></p>

    <div class="no_print">
      <%= link_to 'Print', print_summary_billing_url(@billing.id, format: 'pdf'), class: "styled_links" %>
      <%= link_to 'Excel', print_summary_billing_url(@billing.id, format: 'xls'), class: "styled_links" %>
    </div>

    <div class="clear padding15"></div>

<table class="admin_table" style="width:100%;font-size:10px;">
  <thead>
    <th>Room No</th>
    <th>Occupants</th>
    <th>Room</th>
    <th>Electricity</th>
    <th>Water</th>
    <th>Cable Inst.</th>
    <th>Cable Subs.</th>
    <th>Cable Term.</th>
    <th>Parking</th>
    <th>Cleaning</th>
    <th>Transcient</th>
    <th>Penalty</th>
    <th>Damages</th>
    <th>Lost Key</th>
    <th>Locked Out</th>
    <th>Total</th>
  </thead>
  <tbody>
    <% room, elec, water, installation, subscription, termination, parking, cleaning, transcient, penalty, damages, lost_key, locked_out = 0,0,0,0,0,0,0,0,0,0,0,0,0 %>
    <% room_no = 0 %>
    <% @details.each do |detail| %>
      <% total = 0 %>
      <% if room_no != detail.room_no %>
        <tr>
          <td class="center"><%= detail.room_no %></td>
          <td class="left"><%= "#{detail.first_name} #{detail.last_name}" %></td>
          <td class="right"><%= to_currency(detail.room) %>       <% total += detail.room %></td>
          <td class="right"><%= to_currency(detail.electricity) %><% total += detail.electricity %></td>
          <td class="right"><%= to_currency(detail.water) || 0 %>      <% total += (detail.water || 0) %></td>
          <td class="right"><%= to_currency(detail.installation)%><% total += detail.installation if !detail.installation.blank? %></td>
          <td class="right"><%= to_currency(detail.subscription)%><% total += detail.subscription if !detail.subscription.blank? %></td>
          <td class="right"><%= to_currency(detail.termination) %><% total += detail.termination  if !detail.termination.blank?  %></td>
          <td class="right"><%= to_currency(detail.parking)     %><% total += detail.parking      if !detail.parking.blank?      %></td>
          <td class="right"><%= to_currency(detail.cleaning)    %><% total += detail.cleaning     if !detail.cleaning.blank?     %></td>
          <td class="right"><%= to_currency(detail.transcient)  %><% total += detail.transcient   if !detail.transcient.blank?   %></td>
          <td class="right"><%= to_currency(detail.penalty)     %><% total += detail.penalty      if !detail.penalty.blank?      %></td>
          <td class="right"><%= to_currency(detail.damages)     %><% total += detail.damages      if !detail.damages.blank?      %></td>
          <td class="right"><%= to_currency(detail.lost_key)    %><% total += detail.lost_key     if !detail.lost_key.blank?     %></td>
          <td class="right"><%= to_currency(detail.locked_out)  %><% total += detail.locked_out   if !detail.locked_out.blank?   %></td>
          <td class="right"><%= to_currency(total) %></td>
        </tr>

        <% room += detail.room %>
        <% elec += detail.electricity %>
        <% water+= (detail.water || 0)%>
        <% subscription += detail.subscription if !detail.subscription.blank? %>
        <% installation += detail.installation if !detail.installation.blank? %>
        <% termination  += detail.termination  if !detail.termination.blank?  %>
        <% parking      += detail.parking      if !detail.parking.blank?      %>
        <% cleaning     += detail.cleaning     if !detail.cleaning.blank?     %>
        <% transcient   += detail.transcient   if !detail.transcient.blank?   %>
        <% penalty      += detail.penalty      if !detail.penalty.blank?      %>
        <% damages      += detail.damages      if !detail.damages.blank?      %>
        <% lost_key     += detail.lost_key     if !detail.lost_key.blank?     %>
        <% locked_out   += detail.locked_out   if !detail.locked_out.blank?   %>
        <% room_no = detail.room_no %>

      <% else %>
        <tr>
          <td></td>
          <td class="left"><%= "#{detail.first_name} #{detail.last_name}" %></td>
          <td colspan="14"></td>
        </tr>
      <% end %>
    <% end %>

    <tr>
      <td colspan="2" class="center">Total</td>
      <td class="right"><%= to_currency(room) %></td>
      <td class="right"><%= to_currency(elec) %></td>
      <td class="right"><%= to_currency(water)%></td>
      <td class="right"><%= to_currency(installation) %></td>
      <td class="right"><%= to_currency(subscription) %></td>
      <td class="right"><%= to_currency(termination ) %></td>
      <td class="right"><%= to_currency(parking)      %></td>
      <td class="right"><%= to_currency(cleaning)     %></td>
      <td class="right"><%= to_currency(transcient)   %></td>
      <td class="right"><%= to_currency(penalty)      %></td>
      <td class="right"><%= to_currency(damages)      %></td>
      <td class="right"><%= to_currency(lost_key)     %></td>
      <td class="right"><%= to_currency(locked_out)   %></td>
      <td class="right"><%= to_currency(room+elec+water+installation+subscription+termination+parking+cleaning+transcient+penalty+damages+lost_key+locked_out)%></td>

    </tr>
  </tbody>
</table>

  </div>

  <div class="clear padding15"></div>
</section>

app/views/billings/reports.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>

  <div class="col_3_4 last">
    <!--h3 class="red">Settings</h3-->

    <h3>Billing Summary</h3>

    <p id="notice"><%= notice %></p>

    <table id="billings">
      <thead>
        <tr>
          <th>Statement Date</th>
          <th>Adv Rent Period</th>
          <th>Utilities Period</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @billings.each do |billing| %>
          <tr>
            <td><%= billing.statement_date %><%= "*" if billing.final_billing? %></td>
            <td><%= billing.advance_rent_period %></td>
            <td><%= billing.utilities_reading_period %></td>
            <td>
              <%#= link_to 'Print Statements', billing_billing_details_url(billing) %>
              <%= link_to 'Show', print_summary_billing_url(billing.id) %>
              <%= link_to 'PDF', print_summary_billing_url(billing.id, format: 'pdf') %>
              <%= link_to 'Excel', print_summary_billing_url(billing.id, format: 'xls') %>              
              <%#= link_to 'Destroy', billing, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    </div>

    <span><i>*final billings</i></span>
  <div class="clear padding15"></div>

</section>