config/routes.rb
Rails.application.routes.draw do

  resources :faqs

  get 'admin'   => "checkins#index"
  scope :admin do
    devise_for :users
    resource :setting, only: [:create,:edit, :update,:show]
    resources :rooms do
      get 'vacancies', on: :collection
      resources 'reservations', except: :index
    end
    resources :checkins, except: [:edit,:update,:destroy] do
      post 'new_roommate',    on: :member
      get  'remove_occupant', on: :member
      get  'remove_utility',  on: :member
      get  'vacate',          on: :member
      post 'transfer',        on: :member
      get  'print',           on: :collection
      resources :notices, except: [:index,:destroy]
    end
    resources :occupants
    resources :utilities
    resources :billings do
      resources :billing_details, except: [:new,:create] do
        post 'add_billing_utilities', on: :member
        delete 'remove_billing_utilities', on: :member
        delete 'remove_billing_occupant', on: :member
        post 'add_billing_occupant', on: :member
      end

      get  'electricity_reading', on: :member
      post 'electricity_reading', on: :member
      get  'water_reading', on: :member
      post 'water_reading', on: :member
      get  'reports',         on: :collection
      get  'print_summary',   on: :member
      get  'final_billing',   on: :member
      post 'final_billing',   on: :member
    end
    resources :users, only: :index

    delete 'admin/billings/:billing_id/billing_details_id/:billing_details_id/billing_utilities/:id' => 'billing_details#remove_billing_utilities', as: :remove_billing_utilities

    put 'billings/:billing_id/billing_details/:billing_details_id/add_comment' => 'billing_details#add_comments', as: :add_billing_detail_comments
  end

  match 'contact' => "home#contact", :via => [:get, :post]
  get   'location'=> "home#location"

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    get 'logout',:to => 'devise/sessions#destroy'
  end

  root 'home#index'

  get  '*path' => redirect('/')

end

app/models/room.rb
class Room < ActiveRecord::Base
  validates :room_no,       presence: true, uniqueness:   true
  validates :max_occupants, presence: true, numericality: true
  validates :room_rate,     presence: true, numericality: true
  
  has_many :checkins
  has_many :occupants, through: :checkin_occupants
  has_many :checkin_occupants
  
  has_one  :reservation
  
  def self.all_vacant
    where(occupied: false).order("room_no")
  end
  
  def self.unoccupied
    # do not reverse order of pluck - for select_tag
    where(occupied: false, active: true).pluck(:room_no, :id)
  end
  
  def self.occupied!(room_id)
    find(room_id).update(occupied: 1)
  end
  
  def self.vacated!(room_id)
    find(room_id).update(occupied: 0)
  end
  
  def self.occupancy_list
    Room.where(active: true).includes(checkins: {:checkin_occupants => :occupant}).order(room_no: :asc)
  end
  
  def self.vacancy_list
    Room.find_by_sql("select rooms.room_no,
                             'VACANT' as moveout_date,
                             0 as checkin_id,
                             0 as notice_id,
                             reservations.id as reservation_id,
                             reservations.movein_date as movein_date,
                             reservations.name as name,
                             rooms.id
                        from rooms
                   left join reservations
                          on rooms.id = reservations.room_id
                       where rooms.active = true and
                             rooms.occupied = false
                       UNION
                      select checkins.room_no,
                             notices.moveout_date,
                             checkins.id as checkin_id,
                             notices.id as notice_id,
                             reservations.id as reservation_id,
                             reservations.movein_date as movein_date,
                             reservations.name as name,
                             checkins.room_id
                        from notices,
                             checkins
                   left join reservations
                          on checkins.room_id = reservations.room_id
                       where checkins.id = notices.checkin_id
                    order by room_no;")
  end
  
  def self.room_no(room_id)
    find(room_id).room_no
  end
  
  def self.room_rate(room_id)
    find(room_id).room_rate
  end
  
  def start_date
    if checkins.blank?
      return ''
    else
      checkins.first.start_date
    end
  end
  
  def has_checkin?
    return false if checkins.blank?
    return true
  end
  
  def has_reservation?
    return false if reservation.blank?
    return true
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id

    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_url, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    @room.user_id = current_user.id
    
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to rooms_url, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def vacancies
    @rooms = Room.vacancy_list
    
    respond_to do |format|
      format.html
      format.pdf do
        html = render_to_string(:layout => false, :action => "vacancies.html.erb")
        # many other options
        kit  = PDFKit.new(html, :page_size =>   'Letter')
        # you have to give whole path of stylesheet
        kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/print.css"
        # use disposition inline to open in browser. if removed, will automatically download. Another option is 'inline'
        send_data kit.to_pdf, filename: "vacancies as of #{Date.today}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end
  
  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_no,:max_occupants,:daily_rate,:room_rate,:active,:occupied,:user_id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :room_no %>
    <%= f.text_field :room_no %>
  </p>
  <div class="clear"></div>
  
  <p>
    <%= f.label :max_occupants %>
    <%= f.text_field :max_occupants %>
  </p>
  <div class="clear"></div>
  
  <p>
    <%= f.label :daily_rate %>
    <%= f.text_field :daily_rate %>
  </p>
  <div class="clear"></div>
  
  <p>
    <%= f.label :room_rate %>
    <%= f.text_field :room_rate %>
  </p>
  <div class="clear"></div>
  
  
  <p>
    <%= f.check_box :occupied %>
    <%= f.label :occupied? %>
  </p>
  <div class="clear"></div>
  
  <p>
    <%= f.check_box :active %>
    <%= f.label :active? %>
  </p>
  <div class="clear"></div>

  <div class="actions">
    <%= f.submit %>    <%= link_to 'Cancel', rooms_path, class: "styled_links" %>
  </div>
<% end %>

app/views/rooms/check_in.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>
  
  <div class="col_3_4 last">
    <!--h3 class="red">Settings</h3-->
    
    <h3>Check In</h3>

    <p id="notice"><%= notice %></p>
    
    <%= form_tag '' do %>
      <p>
        <%= label_tag :room_no %>
        <%= select_tag "room_no", options_for_select(@rooms), prompt: "Select room" %>
      </p>
      
      <p>
        <%= label_tag :occupant %>
        <%= select_tag "occupants[]", options_for_select(@occupants.map {|o| [o.to_s, o.id] }), multiple: :multiple, size: 5, prompt: "Select occupant" %>
      </p>
      
      <p>
        <%= label_tag :start_date %>
        <%= date_field_tag :start_date, Date.today %>
      </p>
      
      <p>
        <%= label_tag :basic %><br/>
        <% @basic.all.each do |u| %>
          <%= check_box_tag "utilities[]", u.id , true %> <%= u.name %> <%= to_currency(u.first_rate) %><br/>
        <% end %>
      </p>
        
      <p>
        <%= label_tag :extras %><br/>
        <% @extra.all.each do |u| %>
          <%= check_box_tag "utilities[]", u.id %> <%= u.name %> <%= to_currency(u.first_rate) %><br/>
        <% end %>
      </p>
      
      <%= submit_tag 'New Check In' %>     <%= link_to 'Cancel', occupancy_list_rooms_url, class: "styled_links" %>
    <% end %>
    
    <div class="clear padding15"></div>
    
  </div>
        
  <div class="clear padding15"></div>
</section>  

app/views/rooms/edit.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>
  
  <div class="col_3_4 last">
    <h3 class="red">Editing Rooms</h3>

    <p id="notice"><%= notice %></p>
    
    <%= render 'form' %>
    
  </div>
        
  <div class="clear padding15"></div>
</section>  

app/views/rooms/index.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>
  
  <div class="col_3_4 last">
    <!--h3 class="red">Settings</h3-->
    
    <h3>Room List</h3>
    
    <p id="notice"><%= notice %></p>
    
    <%= link_to 'New Room', new_room_path, class: "styled_links" %>      

    <div class="clear padding20"></div>  
    
    <table id="rooms_list">
      <thead>
        <tr>
          <th>Room No</th>
          <th>Max Occupants</th>
          <th>Monthly Rate</th>
          <th>Daily Rate</th>
          <th>Active?</th>
          <th>Occupied?</th>
          <th colspan="1">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td><%= link_to room.room_no, room %></td>
            <td><%= room.max_occupants %></td>
            <td><%= to_currency(room.room_rate) %></td>
            <td><%= to_currency(room.daily_rate) %></td>
            <td><%= to_status(room.active) %></td>
            <td><%= to_status(room.occupied) %></td>
            <%#= link_to 'Show', room %>
            <td><%= link_to 'Edit', edit_room_path(room) %></td>
            <%#= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %>
          </tr>
        <% end %>
      </tbody>
    </table>
    
  </div>
  
  <%= link_to 'New Room', new_room_path, class: "styled_links" %>      
  
  <div class="clear padding15"></div>
</section>

app/views/rooms/new.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>
  
  <div class="col_3_4 last">
    <!--h3 class="red">Settings</h3-->
    
    <h3>New Room</h3>

    <p id="notice"><%= notice %></p>
    
    <%= render 'form' %>
    
  </div>
        
  <div class="clear padding15"></div>
</section>  

app/views/rooms/occupancy_details.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line no_print">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4 no_print">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>
  
  <div class="col_3_4 last">
    <!--h3 class="red">Settings</h3-->
    
    <h3 class="center no_print">Occupancy Details</h3>

    <p id="notice"><%= notice %></p>
    
    <div class="no_print">
      <%#= link_to 'PRINT', occupancy_details_room_url(@checkin.first, format: "pdf"), class: "styled_links" %> 
    </div>
    
    <div class="clear padding20"></div>

    <p>
      <%= label_tag :room_no %>:
      <%= @checkin.first.room_no %><br/>
      <%= label_tag :start_date %>:
      <%= @checkin.first.start_date %>
    </p>
    <div class="clear padding20"></div>
    
    <h3 class="center">Occupants</h3>
    
    <table>
      <thead>
        <th>Name</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th class="no_print">Actions</th>
      </thead>
      <tbody>
        <% @checkin.each do |occupant| %>
        <tr>
          <td><%= "#{occupant.first_name} #{occupant.last_name}" %></td>
          <td><%= occupant._sdate %></td>
          <td><%= occupant._edate %></td>
          <td class="no_print"><%= link_to 'Remove Occupant', remove_occupant_room_url(occupant.id), data: { confirm: 'Are you sure?' } if occupant._edate.nil? %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    
    <div class="no_print">
      
      <div style="width:auto;display:inline-block">
      <%= form_tag transfer_room_url(@checkin.first.id) do %>
        <%= hidden_field_tag :room_id, @checkin.first.room_id %>
        New Room Number: 
        <%= select_tag "new_room_id", options_for_select(@rooms), prompt: "Select room" %>
        <%= submit_tag 'Tranfer Room' %>
        <%= link_to 'Vacate Room', vacate_room_url(@checkin.first), data: { confirm: 'Are you sure?' }, class: "styled_links" %>
      <% end %>
      
    </div>
      
    </div>
    
    <div class="clear padding20"></div>
    
    <p class="no_print highlight green">'Remove Occupant' is for when an occupant leaves the room, but someone else is left behind. Use 'Vacate Room' for vacating entire room.</p>
    
    <div class="clear padding15"></div>
    
    <h3 class="center">Billing Components</h3>
    
    <table>
      <thead>
        <th>Item</th>
        <th colspan="1" class="no_print">Actions</th>
      </thead>
      <tbody>
        
      <% @details.each do |detail| %>
        <tr>
            <td class="left"><%= detail.utility.name %></td>
            <%#= to_currency(detail.amount) %>
            <%#= detail.start_date %>
            <%#= detail.end_date   %>
            <td class="no_print"><%= link_to 'Remove', remove_utility_room_url(detail.id), data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
    </table>
    <p class="no_print highlight green">These are items added when generating billing statements. Remove one-time items such as Cable TV Installation, Cable TV Termination, Transcient Fees and Damages, and add them as needed.</p>
    
    <p>
      <span><i>Created at <%= @checkin.first.created_at %> by <%= User.last_user(@checkin.first.user_id) %></i></span>
    </p>
    
    
    <div class="clear padding15"></div>
    
    <div class="no_print">
      <%#= link_to 'PRINT', occupancy_details_room_url(@checkin.first, format: "pdf"), class: "styled_links" %> 
    </div>
    
    <div class="clear padding20"></div>
    <div class="clear padding20"></div>
    
    
    <div class="no_print">
    <%= form_tag new_roommate_room_path(id: @checkin.first.id) do %>
      <p>
        <label>New Roommate</label>
        <%= select_tag "occupants[]", options_for_select(@occupants.map {|o| [o.to_s, o.id] }), multiple: :multiple, size: 5, prompt: "Select occupant" %><br/>
      </p>
      
      <p>
        <%= label_tag :start_date %>
        <%= date_field_tag :start_date, Date.today %>
      </p>
    
      <p>
        <%= label_tag :utilities %><br/>
        <% @utilities.each do |u| %>
          <%= check_box_tag "utilities[]", u.id %> <%= u.name %> <%= to_currency(u.first_rate) %><br/>
        <% end %>
      </p>

      <p>     
        <%= submit_tag 'Add' %>
      </p>
      
    <% end %>   
    </div >
  </div>
  
  <div class="clear padding15"></div>
</section>

app/views/rooms/occupancy_list.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line" id="no_print">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4" id="no_print">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>
  
  <div class="col_3_4 last">
    <!--h3 class="red">Settings</h3-->
    
    <h3>Occupancy List</h3>
    
    <div class="no_print">
      <%= link_to 'PRINT', occupancy_list_rooms_url(:format => :pdf) , class: "styled_links "%>
    </div>
    
    <div class="clear padding15"></div>
    
    <ul id="occupancy_list">
      <% @rooms.each do |room| %>
        <% if room.has_checkin? %>
          <li>
            <h2><%= room.room_no %></h2>
            <div id="occupants">
              <%= room.checkins.first.start_date %><br/>
              <% room.checkins.first.occupants.each do |o| %>
                <%= o %><br/>
              <% end %>

            </div>
            <div id="actions" class="no_print">
              <%= link_to 'VIEW DETAILS', occupancy_details_room_path(room.checkins.first) %><br/>
              <%= link_to 'ADD NOTICE TO VACATE' %><br/>
              <%= link_to 'ADD RESERVATION' %><br/>
              <%= link_to 'GENERATE FINAL BILLING' %>
            </div>
          </li>
        <% else %>
          <li>
            <h2><%= room.room_no %></h2>
            <div id="vacant"><%= 'VACANT '%></div>
            <div id="actions" class="no_print">
              <br/><br/>
              <%= link_to 'ADD RESERVATION' %><br/>

            </div>
          </li>  
        <% end %>
      <% end %>
    </ul>

    <div class="clear padding15"></div>

    <div class="no_print">
      <%= link_to 'PRINT', occupancy_list_rooms_url(:format => :pdf) , class: "styled_links "%>
    </div>
    
    <div class="clear padding15"></div>
    
  </div>
        
  <div class="clear padding15"></div>
</section>  

app/views/rooms/show.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>
  
  <div class="col_3_4 last">
    <h3 class="red">Room <%= @room.room_no %></h3>

    <p id="notice"><%= notice %></p>
        
    <p>
      <%= label_tag :max_occupants %><%= @room.max_occupants %>
    </p>
    
    <p>
      <%= label_tag :daily_rate %><%= to_currency(@room.daily_rate) %>
    </p>
    
    <p>
      <%= label_tag :room_rate %><%= to_currency(@room.room_rate) %>
    </p>
    
    <p>
      <%= label_tag :occupied? %><%= to_status(@room.occupied) %>
    </p>
    
    <p>
      <%= label_tag :active? %><%= to_status(@room.active) %>
    </p>
    
    <p>
      <span><i>Last updated at <%= @room.updated_at %> by <%= User.last_user(@room.user_id) %></i></span>
    </p>
          
    <br/>

    <%= link_to 'Edit', edit_room_path(@room), class: "styled_links" %>
    <%= link_to 'Back', rooms_path, class: "styled_links" %>

  </div>
        
  <div class="clear padding15"></div>
</section>

app/views/rooms/vacancies.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix no_print">
    <h1 class="regular brown bottom_line">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4 no_print">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>
  
  <div class="col_3_4 last">
    <h3 class="red">Vacancies</h3>

    <p id="notice"><%= notice %></p>
    
    <div class="no_print">
      <%= link_to 'PRINT', vacancies_rooms_url(:format => :pdf) , class: "styled_links "%>
    </div>
    
    <div class="clear padding20"></div>
    
    <table style='width:100%;'>
      <thead>
        <th>Room No</th>
        <th>Move Out Date</th>
        <th>Reservation</th>
        <th>Move In Date</th>
        <th colspan="2" class="no_print">Actions</th>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td class='center'><%= room.room_no %></td>
            <td class="center"><%= room.moveout_date %></td> 
            <td><%= room.name %></td>
            <td class="center"><%= room.movein_date %></td>     
            <td class="no_print"><%= link_to 'View Notice to Vacate', checkin_notice_url(room.checkin_id, room.notice_id) if room.checkin_id > 0 %></td>
            <td class="no_print"><%= link_to 'View Reservation', room_reservation_url(room.id, room.reservation_id) if !room.reservation_id.blank? %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <div class="no_print">
      <%= link_to 'PRINT', vacancies_rooms_url(:format => :pdf) , class: "styled_links "%>
    </div>
    
    
  </div>
        
  <div class="clear padding15"></div>
</section>  