config/routes.rb
Rails.application.routes.draw do

  resources :faqs

  get 'admin'   => "checkins#index"
  scope :admin do
    devise_for :users
    resource :setting, only: [:create,:edit, :update,:show]
    resources :rooms do
      get 'vacancies', on: :collection
      resources 'reservations', except: :index
    end
    resources :checkins, except: [:edit,:update,:destroy] do
      post 'new_roommate',    on: :member
      get  'remove_occupant', on: :member
      get  'remove_utility',  on: :member
      get  'vacate',          on: :member
      post 'transfer',        on: :member
      get  'print',           on: :collection
      resources :notices, except: [:index,:destroy]
    end
    resources :occupants
    resources :utilities
    resources :billings do
      resources :billing_details, except: [:new,:create] do
        post 'add_billing_utilities', on: :member
        delete 'remove_billing_utilities', on: :member
        delete 'remove_billing_occupant', on: :member
        post 'add_billing_occupant', on: :member
      end

      get  'electricity_reading', on: :member
      post 'electricity_reading', on: :member
      get  'water_reading', on: :member
      post 'water_reading', on: :member
      get  'reports',         on: :collection
      get  'print_summary',   on: :member
      get  'final_billing',   on: :member
      post 'final_billing',   on: :member
    end
    resources :users, only: :index

    delete 'admin/billings/:billing_id/billing_details_id/:billing_details_id/billing_utilities/:id' => 'billing_details#remove_billing_utilities', as: :remove_billing_utilities

    put 'billings/:billing_id/billing_details/:billing_details_id/add_comment' => 'billing_details#add_comments', as: :add_billing_detail_comments
  end

  match 'contact' => "home#contact", :via => [:get, :post]
  get   'location'=> "home#location"

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    get 'logout',:to => 'devise/sessions#destroy'
  end

  root 'home#index'

  get  '*path' => redirect('/')

end

app/models/billing_detail.rb
class BillingDetail < ActiveRecord::Base
  belongs_to :billing
  belongs_to :checkin
  has_many   :billing_utilities, -> { order(:sort_order => :asc)}
  has_many   :occupants, through: :billing_occupants
  has_many   :billing_occupants


  BASIC=['Water','Electricity']

  def add_billing_utility(utility_id, user_id)
    utility = Utility.find(utility_id)
    billing_utilities.create(sort_order: utility.sort_order, utility_name: utility.name, rate:utility.first_rate, amount:utility.first_rate, billing_id: billing.id, user_id: user_id)
  end

  def add_billing_occupant(occupant_id, user_id)
    occupant = Occupant.find(occupant_id)
    billing_occupants.create(billing_detail_id: billing_id , occupant_id: occupant_id, user_id: user_id)
  end

end

app/controllers/billing_details_controller.rb
class BillingDetailsController < ApplicationController
  #before_action :set_billing, only: [:index, :show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @billing = Billing.find(params[:billing_id])
    @billing_details= @billing.billing_details.includes(:billing_utilities,:checkin => {:checkin_occupants => :occupant})



    respond_to do |format|
      format.html
      format.pdf do
        html = render_to_string(:layout => false, :action => "index.html.erb")
        # many other options
        kit  = PDFKit.new(html, :page_size =>   'Letter')
        # you have to give whole path of stylesheet
        kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/print.css"
        # use disposition inline to open in browser. if removed, will automatically download. Another option is 'inline'
        send_data kit.to_pdf, filename: "billing_statements_#{Date.today}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def show
    @billing = Billing.find(params[:billing_id])
    @billing_detail = BillingDetail.where(id: params[:id]).includes(:billing_utilities,:checkin => {:checkin_occupants => :occupant})
    #@billing_detail= @billing.billing_details.where(params[:id]).includes(:billing_utilities,:checkin => {:checkin_occupants => :occupant})
    respond_to do |format|
      format.html
      format.pdf do
        html = render_to_string(:layout => false, :action => "show.html.erb")
        # many other options
        kit  = PDFKit.new(html, :page_size =>   'Letter')
        # you have to give whole path of stylesheet
        kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/print.css"
        # use disposition inline to open in browser. if removed, will automatically download. Another option is 'inline'
        send_data kit.to_pdf, filename: "billing_statements_#{Date.today}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def edit
    @billing = Billing.find(params[:billing_id])
    @billing_detail = BillingDetail.where(id: params[:id]).includes(:billing_utilities,:checkin => {:checkin_occupants => :occupant})
    @utilities      = Utility.all.pluck(:name,:id)
    @occupants      = Occupant.add_to_billing_detail
  end

  def update
    respond_to do |format|
      if BillingUtility.update(params['utilities'].keys, params['utilities'].values)
        format.html { redirect_to billing_billing_detail_url(params[:billing_id], params[:id]), notice: 'Billing was successfully updated.' }
        format.json { render :show, status: :ok, location: @billing_detail }
      else
        format.html { render :edit }
        format.json { render json: @billing_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @billing_detail.billing_utilities.destroy
    respond_to do |format|
      format.html { redirect_to @billing_detail, notice: 'Billing Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_billing_utilities
    return unless request.post?

    if params[:new_billing_utility].blank?
      flash[:notice] = "Please select extras to add"
    else
      billing_detail = BillingDetail.find(params[:id])
      billing_detail.add_billing_utility(params[:new_billing_utility], current_user.id)
      flash[:notice] = "Additional billing charges added successfully"
    end

    redirect_to edit_billing_billing_detail_url(params[:billing_id],params[:id])
  end

  def remove_billing_utilities
    utility = BillingUtility.find(params[:id])
    utility.destroy

    flash[:notice] = "Billing Utility was successfully destroyed."

    redirect_to edit_billing_billing_detail_url(params[:billing_id],params[:billing_details_id])
  end

  def add_comments
    @billing = Billing.find(params[:billing_id])
    @billing_detail = BillingDetail.where(id: params[:billing_details_id]).first
    @billing_detail.comments = params[:add_comment]
    @billing_detail.save

    redirect_to billing_billing_details_url(params[:billing_id]), notice: 'Successfully added comments.'
  end

  def remove_billing_occupant
    occupant = BillingOccupant.find(params[:id])
    occupant.destroy

    flash[:notice] = "Occupant was successfully removed."

    redirect_to edit_billing_billing_detail_url(params[:billing_id],params[:billing_details_id])

  end

  def add_billing_occupant
    return unless request.post?

    if params[:occupant_id].blank?
      flash[:notice] = "Please select occupant to add"
    else
      billing_detail = BillingDetail.find(params[:id])
      billing_detail.add_billing_occupant(params[:occupant_id], current_user.id)
      flash[:notice] = "Additional billing charges added successfully"
    end

    redirect_to edit_billing_billing_detail_url(params[:billing_id],params[:id])
  end



  private

  # Use callbacks to share common setup or constraints between actions.
  def set_billing

  end
end

app/helpers/billing_details_helper.rb
module BillingDetailsHelper
end

app/views/billing_details/_detail.html.erb
   <% room_no = 0 %>
   <% @billing_details.each do |detail| %>
   <div class="billing_statement">

     <%= render partial: 'occupants', locals: { billing: @billing, detail: detail, occupants: detail.occupants } %>

     <%= render partial: 'utilities', locals: { billing_utilities: detail.billing_utilities} %>

     <div class="comments">
       <%= detail.comments %>
     </div>

     <div class="no_print">
     <%= form_tag add_billing_detail_comments_url(@billing.id, detail.id), method: :put do  %>
       <%= text_field_tag :add_comment %>
       <%= submit_tag %>
     <% end %>
     </div>

    <div class="no_print">
      <span><i>Last updated at <%= detail.updated_at %> by <%= User.last_user(detail.user_id) %></i></span>
    </div>

    <div class="clear padding20"></div>

    <table class="print_footer no_border">
      <thead></thead>
      <tbody>
      <tr>
        <td>Received by:</td>
        <td>&nbsp;</td>
        <td>Date received:</td>
      </tr>
      <tr>
        <td class="center"><br/><br/><br/>____________________________________</td>
        <td>&nbsp;</td>
        <td class="center"><br/><br/><br/>____________________________________</td>
      </tr>
      <tr>
        <td class="center">Signature Over Printed Name</td>
        <td>&nbsp;</td>
        <td class="center"></td>
      </tr></tbody>
    </table>

    <%= link_to 'Edit', edit_billing_billing_detail_url(@billing.id, detail.id), class: "styled_links no_print" %>
    <%= link_to 'Print', billing_billing_detail_url(@billing.id, detail.id, format: 'pdf'), class: "styled_links no_print" %>
    <div class="clear padding20"></div>

    <% end %>
  </div>

app/views/billing_details/_form.html.erb
    <p>
      <%= label_tag :room_period %>
      <%= @billing.advance_rent_period %>
    </p>

    <p>
      <%= label_tag :utilities_period %>
      <%= @billing.utilities_reading_period %>
    </p>

    <p>
      <%= label_tag :room_no %>
      <%= @billing_detail.first.room_no %>
    </p>

    <p>
      <%= label_tag :occupants %>
      <% @billing_detail.first.billing_occupants.each do |occupant| %>
        <%= occupant.occupant %>  <%= link_to '(remove)', remove_billing_occupant_billing_billing_detail_url(@billing_detail.first.id, occupant.id), method: :delete, data: { confirm: 'Are you sure?'}, class: "styled_links" %><br/>
      <% end %>
    </p>

    <%= form_tag add_billing_occupant_billing_billing_detail_url(billing_id: @billing.id, id: @billing_detail.first.id) do %>
      <p>
        <label>New Roommate</label>
        <%= select_tag "occupant_id", options_for_select(@occupants.map {|o| [o.to_s, o.id] }), prompt: "Select occupant" %><br/>
        <%= submit_tag 'Add' %>
      </p>

    <% end %>



<div class="clear padding15"></div>

    <div class="narrow">
      <%= label_tag 'sort_order' %>
      <%= label_tag 'utilities' %>
      <%= label_tag 'period' %>
      <%= label_tag 'to' %>
      <%= label_tag 'from' %>
      <%= label_tag 'amount' %>


    <%= form_tag billing_billing_detail_url(@billing.id, @billing_detail.first.id), method: :put do %>
      <% @billing_detail.first.billing_utilities.each do |utility| %>
        <%= fields_for "utilities[]", utility do |f| %>
            <%= f.text_field 'sort_order' %>
            <%= f.text_field 'utility_name' %>
            <%= f.text_field 'utility_period' %>'

            <% if ['Water (minimum)','Water (excess)','Electricity', 'Water (commercial)'].include? utility.utility_name %>
              <%= f.text_field 'to' %>
              <%= f.text_field 'from' %>
            <% else %>
              <%= f.text_field 'end_date', id: 'datepicker' %>
              <%= f.text_field 'start_date', id: 'datepicker2' %>
            <% end %>

            <%= f.text_field 'amount' %>
            <%= link_to 'Remove', remove_billing_utilities_url(@billing.id, @billing_detail.first.id, utility.id), method: :delete, data: { confirm: 'Are you sure?'}, class: "styled_links" %><br/>
        <% end %>

      <% end %>
      <%= submit_tag %> <%= link_to 'Cancel', billing_billing_details_url(@billing.id), class: "styled_links" %>
    <% end %>

    <div class="clear padding15"></div>

    <div style="width:auto;display:inline-block">
    <%= form_tag add_billing_utilities_billing_billing_detail_url(@billing,@billing_detail.first) do %>
      Additional Charges:
      <%= select_tag "new_billing_utility", options_for_select(@utilities), prompt: "Select extras" %>
      <%= submit_tag  %>
    <% end %>

    </div>

app/views/billing_details/_occupants.html.erb
     <table class="billing_statement_hdr no_border">
       <tr>
         <td colspan="2" class="center heading">
           <b>Billing Statement</b><br/>
           As of <%= billing.statement_date %>
         </td>
       </tr>


       <tr>
         <td class="left" style="width:200px;"><b>Room Number:</b></td>
         <td class="left"><%= detail.room_no %></td>
       </tr>
       <tr>
         <td class="left"><b>Occupants:</b></td>
         <td class="left">
           <% occupants.each do |occupant| %>
             <%= occupant.to_s %><br/>
           <% end %>
         </td>
       </tr>

       <tr>
         <td class="left"><b></b></td>
         <td class="left"><%#= billing.advance_rent_period %></td>
       </tr>
       <tr>
         <td class="left"><b></b></td>
         <td class="left"><%#= billing.utilities_reading_period %></td>
       </tr>
     </table>

     <br/><br/>

app/views/billing_details/_utilities.html.erb
     <table>
       <thead>
         <th>Details</th>
         <th>Period</th>
         <th>Present <br/>Reading</th>
         <th>Previous <br/>Reading</th>
         <th>&nbsp;</th>
         <th>Amount</th>
       </thead>
       <tbody>
         <% total = 0 %><% amount = 0 %>
         <% billing_utilities.each do |utility| %>

           <tr>
             <td class="left"><%= utility.utility_name %></td>
             <td class="center"><%= utility.utility_period %></td>

             <% if [WATER_COM,WATER_MIN,ELECTRICITY].include? utility.utility_name %>
               <td class="center" style="width:150px;"><%= utility.to %></td>
               <td class="center" style="width:150px;"><%= utility.from %></td>
               <td class="center" style="width:150px;"><%= utility.to - utility.from %></td>
             <% else %>
               <td class="center" style="width:150px;"><%= utility.end_date %></td>
               <td class="center" style="width:150px;"><%= utility.start_date %></td>
               <td class="center" style="width:150px;">&nbsp;</td>
             <% end %>

             <td class="right" style="width:150px;"><%= to_currency(amount = utility.amount || 0) %><% total = total + amount %></td>
           </tr>

         <% end %>
         <tr>
           <td colspan="5" class="left">TOTAL</td>
           <td class="right"><%= to_currency(total) %></td
         </tr>
      </tbody>
    </table>

app/views/billing_details/edit.html.erb
<section class="container clearfix">
  <header class="container page_info clearfix">
    <h1 class="regular brown bottom_line">Settings</h1>
    <div class="clear"></div>
  </header>
  
  <div class="col_1_4">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>

  <div class="col_3_4 last">
    <h3 class="red">Edit Billing Statement</h3>

    <p id="notice"><%= notice %></p>
    
    <%= render 'form' %>
  </div>
        
  <div class="clear padding15"></div>
</section>  

app/views/billing_details/index.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix no_print">
    <h1 class="regular brown bottom_line">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4 no_print">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>
  
  <div class="col_3_4 last">
    <!--h3 class="red">Settings</h3-->
    
    <h3 class="no_print">Billing Statements</h3>
    
    <p id="notice"><%= notice %></p> 
        
    <%#= link_to 'Electricity Readings', electricity_reading_billing_url(@billing.id), class: "styled_links no_print" %>
    <%#= link_to 'Water Readings', water_reading_billing_url(@billing.id), class: "styled_links no_print" %>
    <%= link_to 'Print Statements', billing_billing_details_url(@billing.id, format: 'pdf'), class: "styled_links no_print" %>
    
   <div class="clear padding20"></div>
   
   <%= render 'detail' %>
      
    <div class="clear padding15"></div>
    
  </div>

</section>

app/views/billing_details/show.html.erb
<!-- START CONTENT -->
<section class="container clearfix">
  <!-- Page Title -->
  <header class="container page_info clearfix no_print">
    <h1 class="regular brown bottom_line">Settings</h1>
    <div class="clear"></div>
  </header>
  <!-- /Page Title -->

  <div class="col_1_4 no_print">
    <%= render :partial => '/shared/menu_sidebar' %>
  </div>

  <div class="col_3_4 last">
    <!--h3 class="red">Settings</h3-->

    <h3 class="no_print">Billing Statement</h3>

    <p id="notice"><%= notice %></p>

   <div class="clear padding20"></div>

   <% room_no = 0 %>

   <div class="billing_statement">

      <%= render partial: 'occupants', locals: { billing: @billing, detail: @billing_detail.first, occupants: @billing_detail.first.occupants } %>

      <%= render partial: 'utilities', locals: { billing_utilities: @billing_detail.first.billing_utilities} %>

      <div class="clear padding15"></div>

      <table class="print_footer no_border">
        <thead></thead>
        <tbody>
        <tr>
          <td>Received by:</td>
          <td>&nbsp;</td>
          <td>Date received:</td>
        </tr>
        <tr>
          <td class="center"><br/><br/><br/>____________________________________</td>
          <td>&nbsp;</td>
          <td class="center"><br/><br/><br/>____________________________________</td>
        </tr>
        <tr>
          <td class="center">Signature Over Printed Name</td>
          <td>&nbsp;</td>
          <td class="center"></td>
        </tr></tbody>
      </table>

    </div>
  </div>
</section>